apiVersion: 1

datasources:
  - name: Managed Prometheus
    type: prometheus
    access: proxy
    url: https://monitoring.googleapis.com/v1/projects/varunai-prod/location/global/prometheus
    isDefault: true
    jsonData:
      authenticationType: gce

  - name: Cloud Trace
    type: tempo
    access: proxy
    url: https://cloudtrace.googleapis.com
    jsonData:
      authenticationType: gce
      tracesToLogsV2:
        datasourceUid: cloud-logging

  - name: Cloud Logging
    type: googlecloud-logging-datasource
    uid: cloud-logging
    access: proxy
    jsonData:
      authenticationType: gce
      defaultProject: varunai-prod
